show databases;

create database retail_customer_behavior;

use retail_customer_behavior;

-- select * from data_set;

-- alter table data_set rename to customer;
-- alter table customer rename to customers;
 
select * from customers;

-- What is the total revenue generated by male vs female customers --
select gender, sum(purchase_amount) as revenue 
from customers
group by gender;


-- Which customers used a discount but still spend more then the average purchase amount --
select customer_id, purchase_amount
from customers
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customers);


-- Which are the top 5 products with the highest avarage review rating --
select item_purchased, round(avg(review_rating),2) as 'Avarage product rating'
from customers
group by item_purchased
order by avg(review_rating)desc
limit 5;


-- Compare the avarage purchase amounts between standard and express shopping --
select shipping_type, 
round(avg(purchase_amount),2)
from customers
where shipping_type in ('Standard', 'Express')
group by shipping_type;


-- Do subscribed customers spend more, Compare avarage spend and total revenue between subscribers and non-subscribers --
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customers
group by subscription_status
order by total_revenue, avg_spend desc;


-- Which 5 products have the highest percentage of purchages with discounts applied --
select item_purchased,
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customers
group by item_purchased
order by discount_rate desc
limit 5;


-- Segment customers into New, Returning and Loyal based on their total number of previous purchases and show the count of each segment --
# (Use CTE function)
with customer_type as (
select customer_id, previous_purchases, 
case
	WHEN previous_purchases = 1 then 'New'
    WHEN previous_purchases between 2 and 10 then 'Returning'
    ELSE 'Loyal'
    END as customer_segment
from customers 
)
select customer_segment, count(*) as 'New of customers'
from customer_type
group by customer_segment;


-- What are the top 3 most purchased products within each category --
# (Use CTE Function)
with item_counts as (
select category, item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customers
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders 
from item_counts
where item_rank <= 3;


-- Customers who are repeat buyers (more then 5 prevous purchases) also likely to subscribe --
select subscription_status,
count(customer_id) as repeat_buyers
from customers 
where previous_purchases > 5 
group by subscription_status;


-- What is the revenue contribution of each age group --
select age_group,
sum(purchase_amount) as total_revenue
from customers 
group by age_group
order by total_revenue desc;

